### ISSUE TITLE
how TIP decodes images in Background

### ISSUE THREAD

**Issue by cjnwan** [twitter/ios-twitter-image-pipeline#10]
in general, images decode in  Background use  CGContextDrawImage or CGDataProviderCopyData method. I read the source code , and find webp use CGDataProviderCopyData, but I don't know other format images how to decodes in Background

**Comment by NSProgrammer** [comment]
Thank you for filing an issue :)

I can't really understand what this issue is, though.  Can you try rephrasing you problem and providing code to illustrate what you are describing?

**Comment by NSProgrammer** [comment]
Closing issue as I don't understand the problem as stated.  Feel free to reopen with more clarifying information.
