### ISSUE TITLE
macOS version?

### ISSUE THREAD

**Issue by vmartinelli** [twitter/ios-twitter-image-pipeline#13]
Hi. Thank you for sharing the library with us. :) Is there any chance we have a compatible Mac version?

**Comment by NSProgrammer** [comment]
Thank you for taking a look :)

At this time there is no priority for macOS support.  Having thought about this a little, I don't think it would be too much work to round hinge out for macOS support.  If anyone had the initiative to submit a PR for macOS support, it would be a great addition.

**Comment by NSProgrammer** [comment]
With Marzipan coming in 2019, we are going to close this request.

**Comment by vmartinelli** [comment]
I think we have different understanding about Marzipan is and what it will be. But, OK then. Your framework your rules. Thank you.

**Comment by NSProgrammer** [comment]
I should have given more context.  This was something under consideration and has effectively been nixed entirely now.

This issue can be reopened and resolved if a PR is provided to add macOS support.  It just won’t be delivered by the internal team and we’re closing the ticket for cleanup
