### ISSUE TITLE
Controlling Animation on TIPImageView

### ISSUE THREAD

**Issue by ken-jen** [twitter/ios-twitter-image-pipeline#18]
Can you point me in the right direction regarding how to control the animations on a TIPImageView that encapsulates an animated GIF?  UIImageView property `isAnimating`, and methods `startAnimating`, `stopAnimating` don't seem to function out of the box.  Ideally, I need to be able to pause / resume the animation.

Thanks for sharing the awesome library!

**Comment by NSProgrammer** [comment]
Yeah, this is a whole in TIP.  TIPImageView doesn't actually take advantage of TIPImageContainer's animation support.  It is a needed improvement.  If someone were interested, they could add this functionality and provide a PR to get it into TIP.

Alternatively, if you have your own animation view or use some other 3rd party animation view... as long as that view subclasses UIImageView, you can use a TIPImageFetchViewHelper with it.

**Comment by ken-jen** [comment]
Thanks for the speedy response.  I'll explore using a 3rd party target for the TIPImageFetchViewHelper for now.  I think the flexibility to do that speaks to a strong design for this framework.  Cheers!

**Comment by NSProgrammer** [comment]
I have a great update here: https://github.com/twitter/ios-twitter-image-pipeline/releases/tag/2.11.0
We now support fetch helper passing the image container which contains all the animation info necessary to animate.
Still need your own implementation of an animated image view, but things just got much easier.

TIP doesn't set out to provide Views, so I'm going to close this issue
