### ISSUE TITLE
Hydration Block Confusion

### ISSUE THREAD

**Issue by ken-jen** [twitter/ios-twitter-image-pipeline#19]
I'm a little lost regarding the intended use of `@property (nullable, nonatomic, copy, readonly) TIPImageFetchHydrationBlock imageRequestHydrationBlock;` on a  `TIPImageFetchRequest` to modify an `NSURLRequest`.  I would expect this block to have a return type of `NSURLRequest`, to allow us to process the request that is passed into the block and return the modified output.  For example, I am currently trying to insert an authentication entry into the header for OAuth2.

Any tips?

**Comment by NSProgrammer** [comment]
To support asynchronous behavior, the hydration block is provided with a completion block.

```
request.imageRequestHydrationBlock = ^(NSURLRequest *URLRequest, id context, TIPImageFetchHydrationCompletionBlock completion) {
    NSMutableURLRequest *mRequest = [URLRequest copy];
    [mRequest setValue:MyOAuthToken() forHTTPHeaderField:@"Authorization"];
    completion(mRequest, nil);
};
```

**Comment by ken-jen** [comment]
Thanks!
