### ISSUE TITLE
Is it suitable for the project which don’t have many different sizes of images?

### ISSUE THREAD

**Issue by yjh1313** [twitter/ios-twitter-image-pipeline#22]
In our project there are not many different sizes of images，just one kind of size，weather the image pipeline is still suitable for  our project ?

**Comment by NSProgrammer** [comment]
Absolutely.  Multi-variant support and optimizations are but one of the many features.  You still get so many other features built in.  See issue #9

**Comment by yjh1313** [comment]
Thanks a lot!

**Comment by yjh1313** [comment]
when different threads accessing to CGContext based functions at the same time will cause sigkill?
