### ISSUE TITLE
Is it possible to set a maximum file size for image download / cacheing?

### ISSUE THREAD

**Issue by ken-jen** [twitter/ios-twitter-image-pipeline#23]
I am wondering if there is a built in, but undocumented, means of setting a maximum file size beyond which images will not be downloaded and/or cached.  Is this possible?

**Comment by NSProgrammer** [comment]
There is not max for what will be downloaded, but we do impose a max "ratio" for the caches.  An image that exceeds the "ratio" would not be cached in the related cache.

See TIPGlobalConfiguration's maxRatioSizeOfCacheEntry

If you have a use case or idea for something different, feel free to flesh it out as a proposal or pull request.

Closing issues as "answered" for now.
