### ISSUE TITLE
tvOS Platform Support

### ISSUE THREAD

**Issue by clstroudtm** [twitter/ios-twitter-image-pipeline#24]
Hi all, I've successfully integrated the current pod into a tvOS project by manually overriding the supported platforms in my local master repo. Is there any reason the podspec couldn't be updated to include `s.tvos.deployment_target = '9.0'`?

**Comment by NSProgrammer** [comment]
We have not tested with tvOS... there are a lot of "OS Version" checks that are specific to iOS.  However, if you would like to create a Pull Request, and validate all the places we do OS Version checks plus create a tvOS unit test to run all the same unit tests with tvOS as the target (should be pretty simple) - we can validate and look at integrating that into the main project (full credit will be attributed to the PR submitter)

**Comment by NSProgrammer** [comment]
This was completed.  Closing
