### ISSUE TITLE
What kind of crash would be triggered when concurrently access to CGContext

### ISSUE THREAD

**Issue by yjh1313** [twitter/ios-twitter-image-pipeline#25]
What kind of crash would be triggered when concurrently access to CGContext

**Comment by NSProgrammer** [comment]
It's not that there would be a crash from that, its that concurrent doing heavy memory operations (often associated with CGContext work in TIP) will use so much memory that the available memory can quickly run out yielding any number of random crash from running out of memory including being purged by the OS.

**Comment by yjh1313** [comment]
thanks a lot
