### ISSUE TITLE
Can't link to app

### ISSUE THREAD

**Issue by lastcc** [twitter/ios-twitter-image-pipeline#28]
ld: '/Users/cc/Library/.../TwitterImagePipeline.framework/TwitterImagePipeline' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/cc/Library/.../TwitterImagePipeline.framework/TwitterImagePipeline' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**This framework was built by carthage and embedded manually.**

Xcode 9.1 beta 2.
iOS 11.1 beta 5.
macOS High Sierra 10.13.1 beta

**Comment by lastcc** [comment]
won't work out with **cocoapods**, too.

ld: framework not found TwitterImagePipeline for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

iOS 11.1 beta 5, Xcode 9.1 beta 2.

App dep. target 11.0

**Comment by lastcc** [comment]
Well, I have 3 targets. The app, the shared lib, the app extension.

the shared lib, which is written by myself to share code, is embedded in the main app and linked against both app extension and main app.

Both my main app target and shard lib target contains `pod 'TwitterImagePipeline'`

**Comment by lastcc** [comment]
The idea behind TIP is amazing. But I just don't have the luck, at the moment.

**Comment by NSProgrammer** [comment]
You might consider cloning the repo or just getting a dump of the code and integrating it into your project/workspace.  We do not use CocoaPods nor Carthage at Twitter and support for those is a convenience that was added by the Open Source community, so I will be unable to personally assist.  (Maybe a nice open source member could take a look?)

I you try integrating directly, I'd be interested in learning in what you observe.  Good Luck!

**Comment by lastcc** [comment]
@NSProgrammer Thanks for the reply. Got that, integrate as submodule should solve this.
