### ISSUE TITLE
Missing description under title

### ISSUE THREAD

**Issue by naeemshaikh90** [twitter/ios-twitter-image-pipeline#4]
![screen shot 2017-03-02 at 12 49 53 pm](https://cloud.githubusercontent.com/assets/10736853/23496935/ca7016da-ff46-11e6-9b9a-c62e7594c713.png)

**Comment by naeemshaikh90** [comment]
We want to add this cool lib into `awesome-ios`.
https://github.com/vsouza/awesome-ios/pull/1522

**Comment by NSProgrammer** [comment]
Thank you for filing the issue.  I have to deal with an OSS curator at Twitter to get that added, which is a pain, but I am trying to get that done ASAP.

**Comment by NSProgrammer** [comment]
Could you add it to awesome-ios without the description in place as I work to add the description?

> Twitter Image Pipeline is a robust and performant image loading and caching framework for iOS clients

**Comment by NSProgrammer** [comment]
well, it's done now :)

**Comment by naeemshaikh90** [comment]
@NSProgrammer Thank you 😀
