### ISSUE TITLE
Signed/Unsiged Build Failure on Xcode 11 beta 1

### ISSUE THREAD

**Issue by eskerber** [twitter/ios-twitter-image-pipeline#43]
Likely due to a "fix" in Clang in the newest beta released today, building TIP in Xcode 11b1 results in the following build error:

```
Comparison of integers of different signs: 'TIPImageLoadSource' (aka 'enum TIPImageLoadSource') and 'const size_t' (aka 'const unsigned long')
```

I will admit I have only used TIP and not familiarized myself with the codebase, but a potential solution is changing `TIPImageLoadSource` to be an `NSUInteger`.

**Comment by NSProgrammer** [comment]
Will be fixed with #45
