### ISSUE TITLE
2.13.0 is the latest version on cocoapods

### ISSUE THREAD

**Issue by cltnschlosser** [twitter/ios-twitter-image-pipeline#52]
Let me know if you need help fixing anything with the cocoapods release project. I can try to help.

**Comment by NSProgrammer** [comment]
Yes, please.  We are spread thin and unable to keep on top of cocoa pods support

**Comment by liamnichols** [comment]
I'm happy to pick this up... I ran `pod spec lint` and it flagged up warnings about unguarded availability checks and after adding `CLANG_WARN_UNGUARDED_AVAILABILITY` to **TwitterImagePipeline.xcconfig** I got the 9 compile errors to show up.

All these errors relate to use of new APIs introduced in iOS 10 so @NSProgrammer would you prefer that I dig into these and look to try and keep iOS 8 and 9 support or can we just bump the minimum iOS deployment target to iOS 10? 

Given that Xcode 12 drops iOS 8 support I think it'll probably be better (and easier) to just support iOS 10+ as we'd have to consider upping it to iOS 9 anyway.. I'm not sure what the official stance on this is though

**Comment by NSProgrammer** [comment]
We have an upcoming release for TIP that will also drop iOS 8 & 9 support.  Let’s wait for that to land.  Hopefully that will make it easier.

**Comment by liamnichols** [comment]
Awesome, that sounds like a good plan. 

Please let me know if there is anything else that you need help with in terms of getting a CocoaPod's release out when the time comes, thanks!

**Comment by NSProgrammer** [comment]
v2.24.0 has been released.  If you are able to update the CocoaPod's for TIP, that would be very welcomed.  Thanks!

**Comment by liamnichols** [comment]
So I listed the spec on `master` and all looks good:

```
$ pod spec lint            

 -> TwitterImagePipeline (2.24.0)
    - NOTE  | [TwitterImagePipeline/Default] xcodebuild:  note: Using new build system
    - NOTE  | [TwitterImagePipeline/Default] xcodebuild:  note: Building targets in parallel
    - NOTE  | [TwitterImagePipeline/Default] xcodebuild:  note: Planning build
    - NOTE  | [TwitterImagePipeline/Default] xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  note: Build description constructed in 0.223138173s
    - NOTE  | [iOS] xcodebuild:  note: Using build description '9985b1ca1524a24f7429e027bb521fa3'
    - NOTE  | [TwitterImagePipeline/Default] xcodebuild:  note: Using eager compilation
    - NOTE  | [TwitterImagePipeline/Default] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')
    - NOTE  | [iOS] [TwitterImagePipeline/Default] xcodebuild:  note: Build description constructed in 0.203846421s
    - NOTE  | [iOS] [TwitterImagePipeline/Default] xcodebuild:  note: Using build description 'b801f9deee45ce8f33e6164b19105d12'

Analyzed 1 podspec.

TwitterImagePipeline.podspec passed validation.
```

Only you (nsprogrammer [at] nsprogrammer [dot] com) or Twitter (cocoapods-owner [at] twitter [dot] com) are listed as owners of this library so you'll have to be the one who runs `pod trunk publish`... It should be as simple as that I think 🙏

**Comment by NSProgrammer** [comment]
OK, should be done.
